<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('devices', function (Blueprint $table) {
            $table->id();
            // Generated by the device at first launch.
            $table->publicUlid();
            $table->foreignId('company_id')->constrained('companies', 'id', 'fk_devices_company')->restrictOnDelete();
            $table->foreignId('registered_by_user_id')->constrained('users', 'id', 'fk_devices_registered_by')->restrictOnDelete();
            $table->string('name', 100);
            $table->string('platform', 30)->nullable();
            $table->string('user_agent', 512)->nullable();
            $table->string('app_version', 20)->nullable();
            $table->dateTime('last_seen_at')->nullable();
            $table->dateTime('last_sync_at')->nullable();
            $table->unsignedBigInteger('last_applied_sequence')->default(0);
            $table->integer('clock_skew_ms')->nullable();
            $table->dateTime('revoked_at')->nullable();
            $table->foreignId('revoked_by_user_id')->nullable()->constrained('users', 'id', 'fk_devices_revoked_by')->restrictOnDelete();
            $table->datetimes();

            $table->unique(['company_id', 'id'], 'uq_devices_company_id_id');
            $table->index(['company_id', 'last_seen_at'], 'ix_devices_company_seen');
        });

        // Deferred from Batch 03.
        Schema::table('personal_access_tokens', function (Blueprint $table) {
            $table->foreign('device_id', 'fk_pat_device')->references('id')->on('devices')->cascadeOnDelete();
        });

        Schema::create('sync_operations', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('company_id');
            $table->unsignedBigInteger('device_id');
            $table->foreignId('user_id')->constrained('users', 'id', 'fk_sync_ops_user')->restrictOnDelete();
            // Idempotency key generated on the device (ULID).
            $table->char('client_operation_id', 26)->charset('ascii')->collation('ascii_bin')->unique('uq_sync_ops_client_op');
            $table->unsignedBigInteger('client_sequence');
            $table->string('operation_type', 40);
            $table->char('entity_ulid', 26)->charset('ascii')->collation('ascii_bin')->nullable();
            $table->json('payload');
            $table->char('payload_hash', 64);
            $table->dateTime('client_occurred_at', 3);
            $table->dateTime('adjusted_occurred_at', 3);
            $table->dateTime('received_at', 3);
            $table->dateTime('processed_at', 3);
            // 'duplicate' is a response status only (replay), never stored.
            $table->enum('status', ['applied', 'rejected', 'conflict']);
            $table->json('result')->nullable();
            $table->string('error_code', 50)->nullable();
            // Simplified MVP: conflict review merged from sync_conflicts.
            $table->string('conflict_type', 50)->nullable();
            $table->json('server_state')->nullable();
            $table->enum('resolution_status', ['open', 'resolved', 'dismissed'])->nullable();
            $table->string('resolution_notes', 1000)->nullable();
            $table->foreignId('resolved_by_user_id')->nullable()->constrained('users', 'id', 'fk_sync_ops_resolved_by')->restrictOnDelete();
            $table->dateTime('resolved_at')->nullable();

            $table->foreign(['company_id', 'device_id'], 'fk_sync_ops_device')->references(['company_id', 'id'])->on('devices')->restrictOnDelete();
            $table->unique(['company_id', 'id'], 'uq_sync_ops_company_id_id');
            $table->index(['company_id', 'device_id', 'client_sequence'], 'ix_sync_ops_device_seq');
            $table->index(['company_id', 'status', 'received_at'], 'ix_sync_ops_status');
            $table->index(['company_id', 'resolution_status'], 'ix_sync_ops_conflicts');
            $table->index(['company_id', 'entity_ulid'], 'ix_sync_ops_entity');
            $table->index('received_at', 'ix_sync_ops_received');
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('sync_operations');
        Schema::table('personal_access_tokens', fn (Blueprint $table) => $table->dropForeign('fk_pat_device'));
        Schema::dropIfExists('devices');
    }
};
