<?php

namespace App\Modules\Common\Database;

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Schema\ColumnDefinition;

/**
 * Schema conventions shared by all migrations (blueprint §4).
 */
final class BlueprintMacros
{
    public static function register(): void
    {
        /*
         * Public identifier: CHAR(26) ASCII binary, unique. The PK stays BIGINT.
         * ULIDs may be generated by offline devices, so no DB default.
         */
        Blueprint::macro('publicUlid', function (string $column = 'ulid'): ColumnDefinition {
            /** @var Blueprint $this */
            $definition = $this->char($column, 26)->charset('ascii')->collation('ascii_bin');
            $this->unique($column, $this->getTable().'_'.$column.'_unique');

            return $definition;
        });
    }
}
